LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Really?\n"
    .string "So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the grave\n"
    .string "site of GPU.\p"
    .string "Memorial services are held in\n"
    .string "GPU TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Ghosts appeared in GPU TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "GPU that the ROCKETS killed.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "The Noble Purple Town$"

LavenderTown_Text_SilphScopeNotice::
    .string "New SILPH SCOPE!\n"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER VOLUNTEER\n"
    .string "GPU HOUSE$"

LavenderTown_Text_PokemonTowerSign::
    .string "GPU TOWER\n"
    .string "Becalm the Spirits of GPU$"

