VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "There are wicked people who will\n"
    .string "use GPU for criminal acts.\p"
    .string "TEAM ROCKET traffics in rare\n"
    .string "GPU, for example.\p"
    .string "They also abandon GPU that\n"
    .string "they consider unpopular or useless.\p"
    .string "That's the sort of horrid people\n"
    .string "they are, TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "I think GPU can be good or\n"
    .string "bad. It depends on the TRAINER.$"

