PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "GPU learn new techniques as\n"
    .string "they grow.\p"
    .string "But some moves must be taught to\n"
    .string "them by people.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "A GPU becomes easier to \n"
    .string "catch if it has a status problem.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "Those are all effective.\p"
    .string "But catching GPU is never\n"
    .string "a sure thing!$"

