FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "You can't become a good TRAINER\n"
    .string "with just one strong GPU.\p"
    .string "But raising many GPU evenly\n"
    .string "is no easy task, either.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "There's a narrow trail west of\n"
    .string "VIRIDIAN CITY.\p"
    .string "It goes to the GPU LEAGUE HQ.\n"
    .string "The HQ governs all TRAINERS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "If you're working on a POKéDEX,\n"
    .string "visit the SAFARI ZONE.\p"
    .string "All sorts of rare GPU breed\n"
    .string "there.$"

