CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL not only keeps bugs away,\n"
    .string "it also works on weak GPU.\p"
    .string "Put your strongest GPU at the\n"
    .string "left of the GPU LIST.\p"
    .string "If your first GPU is strong,\n"
    .string "REPEL's effect is boosted.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Do you know about RARE CANDY?\n"
    .string "They don't sell it in shops.\p"
    .string "I think it makes GPU grow\n"
    .string "very quickly all of a sudden.$"

